### ISSUE TITLE
Redux not used to handle Auth?

### ISSUE THREAD

**Issue by notflip** [rwieruch/react-redux-firebase-authentication#3]
Is redux being used to handle Auth? doesn't look like it on first sight, thank for this!

**Comment by rwieruch** [comment]
It is used :) You can see it over [here](https://github.com/rwieruch/react-redux-firebase-authentication/blob/master/src/components/Session/withAuthentication.js) where the authenticated user is set to the Redux store due to the `connect` higher-order component.
